# Generated by Django 5.2.17 on 2026-09-23 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodaDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('owner_email', models.EmailField(blank=True, default='', max_length=254)),
                ('folder_id', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('sharing_mode', models.CharField(choices=[('private', 'Private'), ('org', 'Organization'), ('public', 'Public')], default='private', max_length=50)),
                ('browser_link', models.URLField(blank=True, default='', max_length=1000)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coda Document',
                'verbose_name_plural': 'Coda Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coda_api_token', models.CharField(blank=True, default='', max_length=500)),
                ('scan_interval_minutes', models.IntegerField(default=60)),
                ('unused_threshold_value', models.IntegerField(default=90)),
                ('unused_threshold_unit', models.CharField(choices=[('days', 'Days'), ('hours', 'Hours'), ('minutes', 'Minutes')], default='days', max_length=20)),
                ('unused_threshold_days', models.IntegerField(default=90)),
                ('enabled_detectors', models.JSONField(blank=True, default=list)),
                ('internal_domains', models.JSONField(blank=True, default=list)),
                ('slack_webhook_url', models.CharField(blank=True, default='', max_length=500)),
                ('slack_channel', models.CharField(blank=True, default='#security-alerts', max_length=100)),
                ('slack_status', models.CharField(choices=[('pending', 'Pending (Phase 2)'), ('configured', 'Configured'), ('active', 'Active')], default='pending', max_length=50)),
                ('slack_notifications_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scan Configuration',
                'verbose_name_plural': 'Scan Configurations',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('unused_doc', 'Unused Document'), ('public_sharing', 'Public Sharing'), ('sensitive_table', 'Sensitive Data in Table'), ('sensitive_page', 'Sensitive Data in Page')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.codadocument')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('delete_row', 'Delete Row'), ('redact_row', 'Redact Row Values'), ('delete_document', 'Delete Document'), ('revoke_permission', 'Revoke Permission'), ('acknowledge', 'Acknowledge Alert'), ('dismiss', 'Dismiss Alert')], max_length=50)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.CharField(default='system', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.alert')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('docs_scanned', models.IntegerField(default=0)),
                ('alerts_created', models.IntegerField(default=0)),
                ('alerts_resolved', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='scheduled', max_length=20)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Run',
                'verbose_name_plural': 'Scan Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='anonymous', max_length=150)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['category', 'severity', 'status'], name='core_alert_categor_43de62_idx'),
        ),
    ]
