# Generated by Django 5.2.17 on 2026-09-23 07:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Security Exposure Report', max_length=255)),
                ('format', models.CharField(choices=[('html', 'HTML Report'), ('pdf', 'PDF Report')], default='html', max_length=10)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export History',
                'verbose_name_plural': 'Export Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
